cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>\d+/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>\d+/', views.cart_remove, name='cart_remove'),
    
]

orders/urls.py
from django.urls import path
from .import views

app_name ='orders'

urlpatterns = [
    path('', views.order_create, name='order_create'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shoper.urls', namespace='shoper')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

shoper/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'shoper'

urlpatterns = [
    path('', views.product_list, name='product_list' ),
    path('shop/', views.shop_all, name='shop' ),
    path('<category_slug>[-\w+]', views.product_list, name='product_list_by_category'),
    path('<int:id>\d+/<slug:slug>[-\w]+)/', views.product_detail, name='product_detail'),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


                         

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from shoper.models import Product

PRODUCT_QUANTITY_CHOICES =[(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    

    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shoper.models import Product
from .cart import Cart
from  .forms import CartAddProductForm

# Create your views here.

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity =cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form']= CartAddProductForm(initial={'quantity': item['quantity'], 'update':True})
    return render(request, 'cart/detail.html',  {'cart':cart})

templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}
<html>
  {% block head %}
        <head>
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css">
            <link rel="stylesheet" href="{% static 'css/detail.css' %}">
            <meta charset="utf-8">
            <title>Your Shopping Cart</title>
        </head>
  {% endblock  %}
  {% block content %}
    <body>
        <h1>Your shopping cart</h1>
        <table style="width:100%"  class = 'cart'>
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Remove</th>
                    <th>Unit</th>
                    <th>Price</th>
                </tr>
            </thead>
        
            <tbody>
                {% for item in cart %}
                    {% with product=item.product %}
                        <tr>
                            <td> 
                                <a href="{{ product.get_absolute_url }}">
                                    <img style="width: 300px;  height: 300px; object-fit: cover;" src ="{% if product.image %}{{ product.image.url }}{% else %}{% static 'image/no_image.jpg' %}{% endif %}">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form action= "{% url 'cart:cart_add' product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update"> 
                                </form>
                            </td>
                            <td><a href="{% url "cart:cart_remove" product.id %}">Remove</a></td>
                            <td class = 'num'>${{ item.price }}</td>
                            <td class='num'>${{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
            </tbody> 
            <tr class ="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class ='num'>${{ cart.get_total_price }}</td>
            </tr>             
        </table>
    </body>
    <p class = 'text-right'>
        <a href="{% url 'shoper:product_list' %}" class = 'button red'> Continue shopping</a>
        <a href="{% url  'orders:order_create' %}"", class = 'button'>Checkout</a>
    </p>
   {% endblock  %}
</html>